### ISSUE TITLE
Torrent boost not working

### ISSUE THREAD

**Issue by mpique** [doshidak/showdex#20] opened 2022-09-15 10:30 UTC
Torrent/Overgrow/Blaze boosts are not being applied to calcs.

**Comment by doshidak** [comment] 2022-09-15 23:47
Ah, HP-based boosts. Might've forgotten about those.

Regardless, thanks for letting me know! I'll keep your issue open until this is fixed.

**Comment by doshidak** [comment] 2022-09-16 06:49
Actually, I realized why we didn't initially show those boosts: they only power-up moves of a certain type only. So it'd be kinda misleading to show the boosted values for ATK/SPA when it only boosts your Water-type moves (in the case of *Torrent*).

(Also fun fact: the calculated stats you see in the Calcdex aren't passed to the internal damage calculator, so they don't affect the damage calculations. Those numbers are purely visual, meant to help you strategize when you look at the SPE, for instance.)

The internal damage calculator does take these into account though, as you can see in the screenshots below.

At 100% HP, *Flare Blitz* does **101.5 - 119.5%**:

![showdex-blaziken-pre-blaze](https://user-images.githubusercontent.com/18254287/190563008-d75ed519-69bb-4c8e-b27c-1765578ed2b0.png)

At 32% HP (below the 1/3 HP [33%] threshold), *Flare Blitz* does **150.7 - 178%**:

![showdex-blaziken-post-blaze](https://user-images.githubusercontent.com/18254287/190563059-a14b3e26-9811-4178-af1b-5cde4beaa33a.png)

Hope that makes sense!

I'll be closing this issue since this is working as intended. (But if you have an idea of how to indicate this in the UI more clearly, feel free to open another issue!)

**Closed by doshidak** 2022-09-16 06:49 UTC
Labels: bug, approved, dank
