### ISSUE TITLE
BUG: alcremie-gmax-gmax-gmax-gmax

### ISSUE THREAD

**Issue by alexakreizinger** [doshidak/showdex#194] opened 2024-03-09 22:06 UTC
just an encountered an odd visual bug where selecting an alcremie's gmax form creates a new option for an alcremie gmax(+1) form, ad infinitum (or at least until I stopped messing with it)

![image](https://github.com/doshidak/showdex/assets/101227699/6cf7cc4d-ee6b-45ed-aaf4-33980fd52ac9)

the initial state shows two options:

[alcremie base / alcremie-gmax]

if you select the option on the right, then open the form selector again, you'll see two new options, but now the active form will be the one on the left:

[alcremie-gmax / alcremie-gmax-gmax]

then if you select the option on the right again, you'll see another two options, and the one on the left will still be active:

[alcremie-gmax-gmax / alcremie-gmax-gmax-gmax]

and so on and so forth. doesn't seem to have any functional impacts though!

**Comment by doshidak** [comment] 2024-07-30 14:49
LOL that's pretty funny actually. we've tried this on our end, but couldn't reproduce it unfortunately. maybe it's cause I've reworked formes a bit for this upcoming release, so may have fixed itself ¯\\\_(ツ)_/¯ anyway, I'll close this with the PR for that release, so feel free to open a new one if this happens again!

thanks c:

**Closed** 2024-07-31 17:12 UTC
Labels: bug, approved, dank
