### ISSUE TITLE
Mr-Mime Galar crashes the extention

### ISSUE THREAD

**Issue by TheDebatingOne** [doshidak/showdex#22] opened 2022-09-17 01:21 UTC
If the lead mon of either teams is Mr-Mime G, or they have it in team preview the extention immidiately crashes. If you have in the back and switch it in/click on its icon to check calcs for it it also crashes. When it crashes it goes blank and shows nothing. I have checked it in AG and gen 8 randbats, don't know if it happens anywhere else but I would assume so. (This app is really cool and I wanted to thank you for making it :))

**Comment by doshidak** [comment] 2022-09-20 05:05
Hmm, interesting!

I did fix Galarian Pokémon holding items not available in Gen 8 (e.g., Z Crystals) for the upcoming v1.0.2 release, but that was frequently occurring in Gen 8 National Dex, where you can find a *Zapdos-Galar* running a *Flyinium Z*.

I'm not sure if that's the case here since you mentioned Gen 8 AG and Randoms. I did look at the Gen 8 Randoms set for *Mr. Mime-Galar* and seems that it's given an *Eviolite*, which broke the Mega item detection (since it ends in -*ite*, interestingly enough), but that was fixed in v1.0.1.

Regardless, I'll take a closer look at this and try to bundle a fix (if determined to still be an issue) with the upcoming release. In the meantime, I'll keep your issue open until I resolve this.

Thanks for the kind words, really happy to hear you're enjoying it! :)

**Comment by doshidak** [comment] 2022-09-23 04:03
Couldn't reproduce the crash unfortunately. Tried it in Gen 8 AG. Maybe one of the fixes in v1.0.2 has fixed the problem with *Mr. Mime-Galar*.

![showdex-mr-mime-galar-screenshot](https://user-images.githubusercontent.com/18254287/191890058-1948d18e-27f0-476b-b3d4-d9a4dc83a54d.png)

If after updating to v1.0.2 you still have this problem (once deployed and approved), feel free to open another issue!

Will close this via reference on the next PR.

**Closed** 2022-09-24 03:18 UTC
Labels: bug, approved, dank
