### ISSUE TITLE
[BUG]: Calcdex stopped counting opponent's Pokemon at 4 mons

### ISSUE THREAD

**Issue by jmynes** [doshidak/showdex#207] opened 2024-07-05 05:34 UTC
https://replay.pokemonshowdown.com/gen3ou-2155438459
![image](https://github.com/doshidak/showdex/assets/15176546/bcdc97ad-b461-4582-bee6-d12e14544a9b)

**Device:** Desktop computer
**OS & Version:** Windows 10, fully up to date
**Browser:** Microsoft Edge (chromium)
**Showdex Version:** v1.2.3
**Format, if applicable:** `[Gen 3] OU

**Comment by doshidak** [comment] 2024-07-30 18:54
most likely a duplicate of #192 w/ nicknames like `"YO !!!"` & `"BIG FRIEND :)"` producing invalid `RegExp`'s.

**Closed** 2024-07-31 17:12 UTC
Labels: bug, dupe, approved, dank
